name: Build example application

on:
  push:
    branches: [ main ]

jobs:  
  build-cli-v2:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F303K8]
        profile: [release]
        

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: build-example-application
        run: |
          set -e
          mbed-tools deploy
          mbed-tools compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}

      - name: Update
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: cmake_build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
